title: Site

tabs:
  main:
    columns:
      - width: 1/1
        sections:
          site-fields:
            type: fields
            fields:
              register_url:
                type: url
                label: Register link URL
                help: External URL for the "Register" nav link. Leave blank to hide it.
          pages:
            type: pages
            label: Pages
